dist: xenial
language: python
python:
  - "3.7"
before_install:
  - cd api
  - pip install pylint
# Install dependencies
install:
  - pip install -r requirements.txt
script: 
  - pylint --disable=R,W assignment_responder.py
