dist: xenial
language: python
python:
  - "3.7"
before_install:
  - cd api
  - pip install pylint
# Install dependencies
install:
  - pip install -r requirements.txt
script: 
  - pylint assignment_responder.py
  - pylint assignment_utilities.py
  - pylint ../utilities/add_users.py
