version: "3.7"
services:
  nginx:
    image: nginx:1.15-alpine
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    depends_on:
      - app
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/api/static
      #- /etc/int_cert:/etc/nginx/ssl
      - /etc/nginx/ssl:/etc/nginx/ssl
    networks:
      - assignment-net
  db:
    image: mysql:8.0.16
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "$MYSQL_PORT:3306"
    user: "8010:8009"
    volumes:
      - $DATA_DIR/$MYSQL_DATABASE:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./sql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - TZ=$TZ
    restart: unless-stopped
    networks:
          - assignment-net
  app:
    image: registry.int.janelia.org/flyem/assignment-manager
    restart: unless-stopped
    depends_on:
      - db
    volumes:
        - static_volume:/api/static
    environment:
      - TZ=$TZ
      - PYTHONUNBUFFERED=1
    networks:
        - assignment-net

networks:
  assignment-net:
      driver: bridge

volumes:
  static_volume:
